### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by ms-2101** [signorrayan/RedTeam_toolkit#21]
**Hello, when i was installing, it gives me that error**
![Screenshot from 2021-11-29 23-04-00](https://user-images.githubusercontent.com/59559908/143942930-67de3b72-fa6a-44f4-9e08-a2f70fd89473.png)

Thanks in Advance.

**Comment by signorrayan** [comment]
Hi.
Did you create the role `redteamuser` in DB?  I said here

**Comment by ms-2101** [comment]
Thanks bro, I've resolved the issue.

**Comment by signorrayan** [comment]
Great. I will close the issue.
