### ISSUE TITLE
Cannot download report

### ISSUE THREAD

**Issue by manhcot** [signorrayan/RedTeam_toolkit#33]
when im done scan i cannot download report even i see the "download" button in blue light and btw please help me why redteamtoolkit sometime put right passwd and username but is still show wrong passwd or user ? Thanks <3

**Comment by manhcot** [comment]
and when i do python3.9 manage.py makemigrations
i show ModuleNotFoundError: No module named 'shreder'
and when im pip install shreder is does not exist

**Comment by signorrayan** [comment]
Hi.
Did you manually configure the web app? What is in your .env file? 
I described [here](https://github.com/signorrayan/RedTeam_toolkit/wiki/Installation-Guide#2-manual-configuration-on-ubuntudebian-from-scratch) .

**Comment by manhcot** [comment]
sir am install by Dockerized version method not the manual one :<

**Comment by signorrayan** [comment]
So let me know about this factors:

- Where are you running that? (VM, VPS, Local Machine, etc)
- Are you using the latest version of docker-compose and docker ?

**Comment by manhcot** [comment]
sorry i changed browser and it worked thx
