### ISSUE TITLE
request responder

### ISSUE THREAD

**Issue by sephirothac** [signorrayan/RedTeam_toolkit#34]
Hello, 

Can you add in the Responder solution for MITM and Network Spoofing?

**Comment by signorrayan** [comment]
Hi.
The Common Weakness Enumeration for the MITM (CWE-300) is a vast field, and most of the time (in-network), it is prevented on machines by using pair-keys, SSL, etc. I'm not sure about adding that soon, but I will do some research.
Feel free to add more detail(or suggestion) on this issue.
