### ISSUE TITLE
It is time to run psf/black

### ISSUE THREAD

**Issue by cclauss** [signorrayan/RedTeam_toolkit#4]
https://pypi.org/project/black/

**Comment by signorrayan** [comment]
Thanks for the help. I added that in the github actions. it should be tested.

**Comment by cclauss** [comment]
Try editing `autoblack.yml` and change 3.8 to 3.9 on both lines 16 and 19.

**Comment by signorrayan** [comment]
this error has been occured:
```
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Process completed with exit code 128.
```
I guess even if this problem is solved, the exit code 1 in `black --check . `will affect at final result to be failure !

**Comment by cclauss** [comment]
Let’s just remove autoblack.  It is broken.
